x-postgresql-volumes: &postgresql-volumes
  - ./postgresql-init-files/init.sql:/docker-entrypoint-initdb.d/init.sql
  - ./volumes-docker-compose/postgresql:/var/lib/postgresql/data

version: '3.7'
services:

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urba
    volumes: *postgresql-volumes